apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002   # must be 30000–32767
