# Generated by Django 5.2.6 on 2025-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror')], max_length=50)),
                ('ReleaseYear', models.IntegerField()),
            ],
        ),
    ]
